I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/player.rpy", line 76, in script
    init python:
  File "game/player.rpy", line 76, in script
    init python:
  File "game/player.rpy", line 77, in <module>
    study = min(player_study_local,100)
NameError: name 'player_study_local' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/player.rpy", line 76, in script
    init python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/player.rpy", line 76, in script
    init python:
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/player.rpy", line 77, in <module>
    study = min(player_study_local,100)
NameError: name 'player_study_local' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Final_Project 1.0
Sat Dec  3 17:13:49 2022
